### ISSUE TITLE
CDN? Changing the base @id URL in the info JSON

### ISSUE THREAD

**Issue by imagemant** [nulib/serverless-iiif#11]
Fantastic project! I am curious if anyone has investigated using it in conjunction with a CDN? I have successfully managed to get the JSON files cached using CloudFront, however, the JSON file contains the original API Gateway endpoint. Any pointers on how I might go about changing the base URL in the JSON file would be much appreciated.

Effectively attempting to change

`"@id":"https://random.execute-api.ap-southeast-1.amazonaws.com/latest/iiif/2/image_name",`

To:

`"@id":"https://random.cloudfront.net/iiif/2/image_name",`

**Comment by mbklein** [comment]
One of the changes currently in the pipeline would use the `X-Forwarded-Host` header instead of the `Host` header if it exists, which will fix this issue. You can change it in your instance by editing [this line](https://github.com/nulib/serverless-iiif/blob/master/src/index.js#L110) to use `this.event.headers['X-Forwarded-Host'] || this.event.headers['Host']` as the value.
